"""Evidence-grounded LLM synthesis for retrieved Personal Brain data."""

from __future__ import annotations

import json
import os
from typing import Any, Iterable
from urllib.request import Request, urlopen

from dotenv import load_dotenv


load_dotenv()


# Demo-safe model fallback chain.
#
# OPENROUTER_MODEL can override the first model.
# The remaining models provide resilience if the preferred provider/model
# is unavailable, out of credits, rate-limited, or otherwise fails.
FALLBACK_MODELS = [
    os.getenv("OPENROUTER_MODEL", "google/gemini-2.5-flash-lite"),
    "google/gemini-2.5-flash-lite",
    "google/gemini-2.5-flash",
]


SYSTEM_PROMPT = """You answer questions about a user's Gmail and Google Drive data.

Use ONLY the supplied source text.

Your job is to answer the user's actual question, not merely describe
the retrieved documents.

You may:
- combine facts from multiple supplied sources;
- compare records;
- determine which record is newest or oldest when dates are present;
- count or summarize records;
- calculate totals when the required values are present;
- identify relationships explicitly supported by the evidence.

Do NOT:
- use outside knowledge;
- invent missing facts;
- assume two records are related merely because they contain similar words;
- infer an attachment, submission, reply, or relationship without evidence.

If the supplied evidence is insufficient to answer the question, answer exactly:
I don't know from the retrieved records.

Return ONLY valid JSON:
{"answer":"concise conversational answer","citations":[{"source":1,"quote":"exact supporting quote"}]}

Every non-refusal answer must contain at least one citation.
The source number must identify one of the supplied sources.
The quote must be copied verbatim from that source.
Prefer citations from both Gmail and Drive when both are material.
"""


def _call_model(
    model: str,
    question: str,
    context: str,
    api_key: str,
) -> dict[str, Any]:
    """Call one OpenRouter model and return the decoded response."""

    request = Request(
        "https://openrouter.ai/api/v1/chat/completions",
        data=json.dumps(
            {
                "model": model,
                "max_tokens": 2000,
                "temperature": 0,
                "messages": [
                    {
                        "role": "system",
                        "content": SYSTEM_PROMPT,
                    },
                    {
                        "role": "user",
                        "content": (
                            f"Question: {question}\n\n"
                            f"Sources:\n{context}"
                        ),
                    },
                ],
            }
        ).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "X-OpenRouter-Title": "Personal Brain",
        },
        method="POST",
    )

    with urlopen(request, timeout=30) as response:
        raw_response = response.read().decode("utf-8")

    return json.loads(raw_response)


def _extract_model_payload(
    response_json: dict[str, Any],
) -> dict[str, Any]:
    """Extract the JSON answer generated by the model."""

    content = response_json["choices"][0]["message"]["content"]

    # Some providers occasionally wrap JSON in a markdown code fence.
    # Remove the fence without changing the actual payload.
    content = content.strip()

    if content.startswith("```") and content.endswith("```"):
        lines = content.splitlines()

        if lines and lines[0].strip().startswith("```"):
            lines = lines[1:]

        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]

        content = "\n".join(lines).strip()

    payload = json.loads(content)

    if not isinstance(payload, dict):
        raise ValueError("Model response was not a JSON object.")

    return payload


def _validate_citations(
    payload: dict[str, Any],
    items: list[dict[str, Any]],
    source_texts: list[str],
) -> dict[str, Any] | None:
    """Validate model citations against the exact supplied source text."""

    answer = payload.get("answer", "")
    citations = payload.get("citations", [])

    if not isinstance(answer, str):
        return None

    answer = answer.strip()

    if not answer:
        return None

    if answer == "I don't know from the retrieved records.":
        return {
            "answer": answer,
            "citations": [],
        }

    if not isinstance(citations, list) or not citations:
        return None

    validated: list[dict[str, Any]] = []

    for citation in citations:
        if not isinstance(citation, dict):
            return None

        source_index = citation.get("source")
        quote = citation.get("quote", "")

        if (
            not isinstance(source_index, int)
            or not 1 <= source_index <= len(source_texts)
        ):
            return None

        if (
            not isinstance(quote, str)
            or not quote.strip()
            or quote not in source_texts[source_index - 1]
        ):
            return None

        item = items[source_index - 1]

        validated.append(
            {
                "source": source_index,
                "source_type": item["source_type"],
                "title": item["title"],
                "quote": quote,
            }
        )

    return {
        "answer": answer,
        "citations": validated,
    }


def synthesize_answer_with_citations(
    question: str,
    evidence: Iterable[dict[str, Any]],
    fallback: str,
) -> dict[str, Any]:
    """Synthesize an answer from retrieved evidence.

    The model only receives retrieved source text. Model-generated citations
    are validated against that exact text before they are returned.
    """

    items = list(evidence)

    if not items:
        return {
            "answer": "I don't know from the retrieved records.",
            "citations": [],
        }

    api_key = os.getenv("OPENROUTER_API_KEY")
    enabled = (
        os.getenv("PERSONAL_BRAIN_ENABLE_SYNTHESIS", "").lower()
        in {"1", "true", "yes"}
    )

    # Deterministic fallback when synthesis is disabled or unavailable.
    if not api_key or not enabled:
        return {
            "answer": fallback,
            "citations": [
                {
                    "source": index,
                    "source_type": item["source_type"],
                    "title": item["title"],
                    "quote": item["excerpt"],
                }
                for index, item in enumerate(items, start=1)
            ],
        }

    # Keep the context bounded so the model receives only a manageable amount
    # of retrieved evidence.
    source_texts = [
        str(item["text"])[:6_000]
        for item in items
    ]

    context = "\n\n".join(
        (
            f"--- SOURCE {index} "
            f"({item['source_type']}: {item['title']}) ---\n"
            f"{text}"
        )
        for index, (item, text) in enumerate(
            zip(items, source_texts),
            start=1,
        )
    )

    last_error: Exception | None = None

    # Try the configured/preferred model first, then the demo-safe fallbacks.
    # Duplicate model names are removed while preserving order.
    models: list[str] = []

    for model in FALLBACK_MODELS:
        if model and model not in models:
            models.append(model)

    for model in models:
        try:
            response_json = _call_model(
                model=model,
                question=question,
                context=context,
                api_key=api_key,
            )

            payload = _extract_model_payload(response_json)

            validated = _validate_citations(
                payload,
                items,
                source_texts,
            )

            if validated is not None:
                return validated

        except Exception as exc:
            last_error = exc
            continue

    # If every model failed, return the deterministic retrieval answer.
    #
    # Do not expose provider errors to the user: they are implementation
    # details and the application still has grounded evidence available.
    _ = last_error

    return {
        "answer": fallback,
        "citations": [],
    }


def synthesize_answer(
    question: str,
    evidence: Iterable[str],
    fallback: str,
    source_name: str,
) -> str:
    """Backward-compatible single-source synthesis used by existing modules."""

    items = [
        {
            "source_type": source_name.lower(),
            "title": source_name,
            "text": text,
            "excerpt": text[:500],
        }
        for text in evidence
    ]

    return synthesize_answer_with_citations(
        question,
        items,
        fallback,
    )["answer"]